// code generated by [generate-resource-dart-code] vscode-extension.
class AssetsImages {
  static const buttonChatPng = 'assets/images/button_chat.png';
  static const cartVariantPng = 'assets/images/cart-variant.png';
  static const circleUsernamePng = 'assets/images/circle_username.png';
  static const gambarTextPng = 'assets/images/gambar_text.png';
  static const headsetPng = 'assets/images/headset.png';
  static const iconAccountFullnamePng = 'assets/images/icon_account_fullname.png';
  static const iconAccountProfileNavigationBarPng = 'assets/images/icon_account_profile_navigation_bar.png';
  static const iconArrowBagPng = 'assets/images/icon-arrow_bag.png';
  static const iconArrowLeftPng = 'assets/images/icon_arrow_left.png';
  static const iconArrowRigthPng = 'assets/images/icon_arrow_rigth.png';
  static const iconCartNavigationBarPng = 'assets/images/icon_cart_navigation_bar.png';
  static const iconCeklishPng = 'assets/images/icon_ceklish.png';
  static const iconChatNavigationBarPng = 'assets/images/icon_chat_navigation_bar.png';
  static const iconEmailBlackForSignUpPng = 'assets/images/icon_email_black_for_sign_up.png';
  static const iconEmailPng = 'assets/images/icon_email.png';
  static const iconHomeNavigationBarPng = 'assets/images/icon_home_navigation_bar.png';
  static const iconLoveHandNavigationDartPng = 'assets/images/icon_love_hand_navigation-dart.png';
  static const iconLovedSingleFavoriteDetailsPng = 'assets/images/icon_loved_single_favorite_details.png';
  static const iconPasswordBlackSignUpPng = 'assets/images/icon_password_black_sign_up.png';
  static const iconPasswordPng = 'assets/images/icon_password.png';
  static const iconProfileChatMessagePng = 'assets/images/icon_profile_chat_message.png';
  static const iconProfileRedPng = 'assets/images/icon_profile_red.png';
  static const iconRemovePng = 'assets/images/icon_remove.png';
  static const iconSmaleLovedFavoriteDetailsPng = 'assets/images/icon_smale_loved_favorite_details.png';
  static const iconStoreLocationPng = 'assets/images/icon_store_location.png';
  static const iconXPng = 'assets/images/icon_x.png';
  static const iconYourAddresPng = 'assets/images/icon_your_addres.png';
  static const logoGoternoPng = 'assets/images/logo_goterno.png';
  static const logoutPng = 'assets/images/logout.png';
  static const loveWhitePng = 'assets/images/love_white.png';
  static const minPng = 'assets/images/min.png';
  static const nasipadangWebp = 'assets/images/nasipadang.webp';
  static const profileIconChatPng = 'assets/images/profile_icon_chat.png';
  static const tambahPng = 'assets/images/tambah.png';
  static const teleponPng = 'assets/images/telepon.png';
  static const tombolPng = 'assets/images/tombol.png';
  static const tombolXPng = 'assets/images/tombolX.png';
}

class AssetsSvgs {

}

